### ISSUE TITLE
Error in validate-appconfig.py

### ISSUE THREAD

**Issue by dsugar100** [SELinuxProject/refpolicy#819]
I'm seeing the following error when running validate-appconfig.py.  I'm on a RHEL9 system.

Validating clip file contexts.                                                                                                                        
/sbin/setfiles -q -c tmp/policy.bin tmp/all_mods.fc
Validating clip appconfig.                                                                                                                            
python3 -bb -t -t -E -W error support/validate-appconfig.py -c /usr/bin/chkcon -l -s -v -x tmp/appconfig tmp/policy.bin
Traceback (most recent call last):                                         
  File "/builddir/build/BUILD/clip-selinux-policy-9.1.0.5/support/validate-appconfig.py", line 42, in <module>                                            class ContextValidator:                                                                                                                             
File "/builddir/build/BUILD/clip-selinux-policy-9.1.0.5/support/validate-appconfig.py", line 46, in ContextValidator                                    def __init__(self, /, policy_path: str | None = None, *,                                                                                          
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'                                                                                   
make: *** [Rules.modular:228: validate] Error 1                                                                                                       
error: Bad exit status from /var/tmp/rpm-tmp.BOvrtp (%install)                                                                                        
    Bad exit status from /var/tmp/rpm-tmp.BOvrtp (%install)
                                                                           
Ideas?

**Comment by dsugar100** [comment]
RHEL9 has python 3.9.  Testing on Fedora which as python3.11 seems to work ok.

**Comment by dsugar100** [comment]
Ok, looks like the 'str | None' syntax was added in 3.10.  I will see if I can update to work with 3.9.

**Comment by pebenito** [comment]
I think this tool will instead have to be disabled if you're building on Python 3.9; see #816. It pulls in SETools, which requires 3.10.
